import { useMemo, useState } from "react";
import { Link } from "wouter";
import { CheckCircle2, ChevronRight, CreditCard, Download, FileText, MoreHorizontal, PackageOpen, Plus, Search, ShieldCheck, Users, XCircle } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Avatar, PageHeader, SectionHeader, StatusBadge, TableSearch, downloadCsv } from "@/components/dashboard-ui";
import { QuickFormDialog } from "@/components/ActionDialogs";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { allInvoices, plans, products, subscriptions, teamMembers, formatCurrency, type Invoice } from "@/data/mockData";
import { toast } from "sonner";

export function Subscriptions() {
  const [filter, setFilter] = useState("All");
  const [query, setQuery] = useState("");
  const filtered = subscriptions.filter((item) => (filter === "All" || item.status === filter || (filter === "Renewal Due" && item.renewalDate.includes("Sep 2026"))) && item.customer.toLowerCase().includes(query.toLowerCase()));
  const exportRows = () => {downloadCsv("subscriptions.csv", filtered as unknown as Record<string,string|number|boolean>[]);toast.success("Subscriptions exported")};
  return <AppShell breadcrumbs={["Billing","Subscriptions"]}><PageHeader eyebrow="Billing operations" title="Subscriptions" description="Manage recurring contracts, upcoming renewals, payment state, and plan changes." actions={<Button size="sm" onClick={() => toast.success("Subscription wizard opened")}><Plus className="size-3.5"/>Create subscription</Button>}/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Active subscriptions","1,142","+7.8%",CreditCard],["MRR","₹2.48Cr","+6.2%",CheckCircle2],["Renewing in 30 days","48","₹36.2L",ShieldCheck],["Past due","17","₹8.4L",XCircle]].map(([l,v,d,I])=><div className="metric-card" key={l as string}><div className="flex items-center justify-between text-[10px] font-semibold uppercase tracking-wider text-muted-foreground"><span>{l as string}</span><I className="size-3.5"/></div><div className="mt-4 font-tabular text-2xl font-semibold">{v as string}</div><div className="mt-1 text-[10px] text-muted-foreground">{d as string}</div></div>)}</div><div className="mt-4 panel overflow-hidden"><TableSearch value={query} onChange={setQuery} placeholder="Search subscriptions…" actions={<><Select value={filter} onValueChange={setFilter}><SelectTrigger className="h-8 w-[135px] bg-card text-xs"><SelectValue/></SelectTrigger><SelectContent>{["All","Active","Trial","Renewal Due","Past due"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" className="h-8 bg-card text-xs" onClick={exportRows}><Download className="size-3.5"/>Export</Button></>}/><div className="overflow-x-auto"><table className="data-table min-w-[1050px]"><thead><tr><th>Customer</th><th>Plan</th><th>Status</th><th>Start date</th><th>Renewal</th><th>Cycle</th><th className="text-right">MRR</th><th className="text-right">Contract</th><th>Payment</th><th>Auto renew</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.customerId}><td><Link href={`/customers/${item.customerId}`} className="font-medium hover:underline">{item.customer}</Link><div className="font-mono text-[9px] text-muted-foreground">{item.customerId}</div></td><td>{item.plan}</td><td><StatusBadge status={item.status}/></td><td>{item.startDate}</td><td>{item.renewalDate}</td><td>{item.cycle}</td><td className="text-right font-tabular font-medium">{formatCurrency(item.mrr)}</td><td className="text-right font-tabular">{formatCurrency(item.amount)}</td><td><StatusBadge status={item.payment}/></td><td><Switch defaultChecked={item.autoRenewal} onCheckedChange={()=>toast.success("Auto-renewal preference updated")}/></td><td><ActionMenu items={["View subscription","Change plan","Renew","View invoices"]}/></td></tr>)}</tbody></table></div></div></AppShell>;
}

export function ProductsPlans() {
  const [tab, setTab] = useState<"products"|"plans">("products");
  return <AppShell breadcrumbs={["Billing","Products & Plans"]}><PageHeader eyebrow="Billing catalog" title="Products & Plans" description="Define the commercial catalog, limits, and feature packaging used by customer subscriptions." actions={<QuickFormDialog type="product" title={tab==="products"?"Create product":"Create plan"} description="Add a new item to the mock billing catalog." trigger={<Button size="sm"><Plus className="size-3.5"/>Create {tab==="products"?"product":"plan"}</Button>}/>}/><div className="mt-4 flex gap-1 border-b"><button className={`tab-button ${tab==="products"?"active":""}`} onClick={()=>setTab("products")}>Products <span>{products.length}</span></button><button className={`tab-button ${tab==="plans"?"active":""}`} onClick={()=>setTab("plans")}>Plans <span>{plans.length}</span></button></div>{tab==="products"?<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{products.map(item=><div className="panel group p-4" key={item.name}><div className="flex items-start justify-between"><span className="grid size-9 place-items-center rounded-lg border bg-muted/35"><PackageOpen className="size-4"/></span><ActionMenu items={["Edit product","Duplicate","Archive"]}/></div><h3 className="mt-4 text-sm font-semibold">{item.name}</h3><p className="mt-1 h-10 text-[10px] leading-5 text-muted-foreground">{item.category} capabilities billed through a {item.model.toLowerCase()} model.</p><div className="mt-4 grid grid-cols-2 border-t pt-3 text-[10px]"><div><span className="text-muted-foreground">Customers</span><b className="mt-1 block font-tabular text-sm">{item.customers}</b></div><div><span className="text-muted-foreground">Plans</span><b className="mt-1 block font-tabular text-sm">{item.plans}</b></div></div><div className="mt-3 flex items-center justify-between"><StatusBadge status={item.status}/><span className="text-[9px] text-muted-foreground">{item.model}</span></div></div>)}</div>:<div className="mt-4 panel overflow-hidden"><div className="p-4 pb-2"><SectionHeader title="Plan catalog" description="Pricing, limits, and commercial availability"/></div><div className="overflow-x-auto"><table className="data-table min-w-[850px]"><thead><tr><th>Plan</th><th>Product</th><th className="text-right">Monthly</th><th className="text-right">Annual</th><th>Usage limit</th><th className="text-right">Features</th><th>Status</th><th/></tr></thead><tbody>{plans.map(item=><tr key={item.name}><td className="font-medium">{item.name}</td><td>{item.product}</td><td className="text-right font-tabular">{item.monthly?formatCurrency(item.monthly):"Custom"}</td><td className="text-right font-tabular">{item.annual?formatCurrency(item.annual):"Custom"}</td><td>{item.limit}</td><td className="text-right font-tabular">{item.features}</td><td><StatusBadge status={item.status}/></td><td><ActionMenu items={["Edit plan","Duplicate","Archive"]}/></td></tr>)}</tbody></table></div></div>}</AppShell>;
}

export function Invoices() {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("All statuses"); const [selected,setSelected]=useState<(typeof allInvoices)[number]|null>(null);
  const filtered=allInvoices.filter(x=>(status==="All statuses"||x.status===status)&&`${x.id} ${x.customer}`.toLowerCase().includes(query.toLowerCase()));
  const exportRows=()=>{downloadCsv("invoices.csv",filtered.map(x=>({Invoice:x.id,Customer:x.customer,Date:x.date,Total:x.total,Status:x.status})));toast.success("Invoices exported")};
  return <AppShell breadcrumbs={["Billing","Invoices"]}><PageHeader eyebrow="Billing operations" title="Invoices" description="Track issued, paid, overdue, and cancelled customer invoices." actions={<Button size="sm" onClick={()=>toast.success("Invoice draft created")}><Plus className="size-3.5"/>Create invoice</Button>}/><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Billed this month","₹2.86Cr","+8.4%"],["Collected","₹2.64Cr","92.4%"],["Outstanding","₹21.6L","32 invoices"],["Overdue","₹8.4L","17 invoices"]].map(([l,v,d])=><div className="metric-card" key={l}><div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{l}</div><div className="mt-4 font-tabular text-2xl font-semibold">{v}</div><div className="mt-1 text-[10px] text-muted-foreground">{d}</div></div>)}</div><div className="mt-4 panel overflow-hidden"><TableSearch value={query} onChange={setQuery} placeholder="Search invoice or customer…" actions={<><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-8 w-[140px] bg-card text-xs"><SelectValue/></SelectTrigger><SelectContent>{["All statuses","Draft","Sent","Paid","Overdue","Cancelled"].map(x=><SelectItem value={x} key={x}>{x}</SelectItem>)}</SelectContent></Select><Button variant="outline" size="sm" className="h-8 bg-card text-xs" onClick={exportRows}><Download className="size-3.5"/>Export</Button></>}/><div className="overflow-x-auto"><table className="data-table min-w-[1000px]"><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Due date</th><th>Product</th><th className="text-right">Amount</th><th className="text-right">Tax</th><th className="text-right">Total</th><th>Status</th><th>Payment date</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={`${item.customerId}-${item.id}`}><td className="font-mono text-[10px]">{item.id}</td><td><Link href={`/customers/${item.customerId}`} className="font-medium hover:underline">{item.customer}</Link></td><td>{item.date}</td><td>{item.dueDate}</td><td>{item.product}</td><td className="text-right font-tabular">{formatCurrency(item.amount)}</td><td className="text-right font-tabular">{formatCurrency(item.tax)}</td><td className="text-right font-tabular font-medium">{formatCurrency(item.total)}</td><td><StatusBadge status={item.status}/></td><td>{item.paymentDate||"—"}</td><td><Button variant="ghost" size="sm" className="h-7 text-[10px]" onClick={()=>setSelected(item)}>View <ChevronRight className="size-3"/></Button></td></tr>)}</tbody></table></div></div><InvoiceDetail row={selected} onClose={()=>setSelected(null)}/></AppShell>;
}

export function Team() {
  const [query,setQuery]=useState(""); const rows=teamMembers.filter(x=>`${x.name} ${x.email} ${x.role}`.toLowerCase().includes(query.toLowerCase()));
  return <AppShell breadcrumbs={["Workspace","Team"]}><PageHeader eyebrow="Workspace" title="Team" description="Manage internal access, roles, departments, and customer assignments." actions={<QuickFormDialog title="Invite team member" description="Invite a colleague to this mock workspace." trigger={<Button size="sm"><Plus className="size-3.5"/>Invite member</Button>}/>}/><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="metric-card"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Active members</div><div className="mt-3 font-tabular text-2xl font-semibold">38</div><div className="mt-1 text-[10px] text-muted-foreground">Across 7 roles</div></div><div className="metric-card"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Customer owners</div><div className="mt-3 font-tabular text-2xl font-semibold">16</div><div className="mt-1 text-[10px] text-muted-foreground">1,284 customers assigned</div></div><div className="metric-card"><div className="text-[10px] uppercase tracking-wider text-muted-foreground">Pending invites</div><div className="mt-3 font-tabular text-2xl font-semibold">3</div><div className="mt-1 text-[10px] text-muted-foreground">Oldest 4 days ago</div></div></div><div className="mt-4 panel overflow-hidden"><TableSearch value={query} onChange={setQuery} placeholder="Search team members…"/><div className="overflow-x-auto"><table className="data-table min-w-[850px]"><thead><tr><th>Member</th><th>Email</th><th>Role</th><th>Department</th><th className="text-right">Customers</th><th>Status</th><th>Last active</th><th/></tr></thead><tbody>{rows.map(item=><tr key={item.email}><td><div className="flex items-center gap-2.5"><Avatar initials={item.initials}/><span className="font-medium">{item.name}</span></div></td><td>{item.email}</td><td><span className="rounded-md border bg-muted/30 px-2 py-1 text-[10px] font-medium">{item.role}</span></td><td>{item.department}</td><td className="text-right font-tabular">{item.customers}</td><td><StatusBadge status={item.status}/></td><td>{item.lastActive}</td><td><ActionMenu items={["Edit role","View activity","Disable member"]}/></td></tr>)}</tbody></table></div></div></AppShell>;
}

function ActionMenu({items}:{items:string[]}){return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="size-7"><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{items.map((item,index)=><div key={item}>{index===items.length-1&&item.toLowerCase().includes("archive")?<DropdownMenuSeparator/>:null}<DropdownMenuItem className={item.toLowerCase().includes("cancel")||item.toLowerCase().includes("disable")||item.toLowerCase().includes("archive")?"text-rose-600":""} onClick={()=>toast.success(`${item} opened`)}>{item}</DropdownMenuItem></div>)}</DropdownMenuContent></DropdownMenu>}
function InvoiceDetail({row,onClose}:{row:(typeof allInvoices)[number]|null;onClose:()=>void}){return <Dialog open={!!row} onOpenChange={open=>!open&&onClose()}><DialogContent className="sm:max-w-[540px]"><DialogHeader><DialogTitle>Invoice {row?.id}</DialogTitle><DialogDescription>{row?.customer} · {row?.product}</DialogDescription></DialogHeader>{row&&<div><div className="rounded-xl bg-foreground p-5 text-background"><div className="text-[9px] uppercase tracking-wider opacity-60">Total due</div><div className="mt-2 text-3xl font-semibold">{formatCurrency(row.total)}</div><div className="mt-4 flex items-center justify-between text-xs"><span>Due {row.dueDate}</span><StatusBadge status={row.status}/></div></div><div className="mt-4 divide-y rounded-lg border text-xs">{[["Subtotal",formatCurrency(row.amount)],["Tax",formatCurrency(row.tax)],["Total",formatCurrency(row.total)]].map(([l,v])=><div className="flex justify-between p-3" key={l}><span className="text-muted-foreground">{l}</span><b>{v}</b></div>)}</div><div className="mt-4 flex justify-end gap-2"><Button variant="outline" onClick={()=>toast.success("PDF downloaded")}><Download className="size-4"/>Download</Button><Button onClick={()=>toast.success("Invoice opened")}>Open invoice</Button></div></div>}</DialogContent></Dialog>}
