import { useState } from "react";
import { Bell, Building2, Check, ChevronRight, CreditCard, KeyRound, Lock, Moon, Palette, Save, Shield, Sun, UserRound, Users, Zap } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Avatar, PageHeader, SectionHeader } from "@/components/dashboard-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { useApp } from "@/contexts/AppContext";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

const groups=[
  {label:"Account",items:[["Profile",UserRound],["Password",Lock],["Preferences",Zap]]},
  {label:"Workspace",items:[["Workspace",Building2],["Team",Users],["Roles & permissions",Shield]]},
  {label:"Product",items:[["Channels",Zap],["Notifications",Bell],["Usage settings",CreditCard]]},
  {label:"Billing",items:[["Billing information",CreditCard],["Invoice preferences",CreditCard]]},
  {label:"Security",items:[["Login security",Lock],["Sessions",Shield],["API keys",KeyRound]]},
  {label:"Appearance",items:[["Theme",Palette]]},
] as const;

export default function Settings(){const [section,setSection]=useState("Profile"); return <AppShell breadcrumbs={["Settings",section]}><PageHeader eyebrow="Workspace configuration" title="Settings" description="Manage personal preferences, workspace controls, security, billing, and appearance."/><div className="mt-4 grid gap-6 lg:grid-cols-[215px_minmax(0,1fr)]"><aside className="space-y-4">{groups.map(group=><div key={group.label}><div className="mb-1 px-2 text-[9px] font-semibold uppercase tracking-[.14em] text-muted-foreground">{group.label}</div>{group.items.map(([name,Icon])=><button key={name} onClick={()=>setSection(name)} className={cn("settings-nav",section===name&&"active")}><Icon className="size-3.5"/><span>{name}</span>{section===name&&<ChevronRight className="ml-auto size-3"/>}</button>)}</div>)}</aside><section className="min-w-0">{section==="Profile"?<Profile/>:section==="Theme"?<ThemeSettings/>:section==="Notifications"?<NotificationSettings/>:section==="Login security"?<SecuritySettings/>:<GenericSettings section={section}/>}</section></div></AppShell>}

function Profile(){return <SettingsCard title="Profile" description="Your personal information and workspace identity."><div className="flex items-center gap-4 border-b pb-5"><Avatar initials="AS" size="lg"/><div><div className="text-sm font-semibold">Anika Shah</div><div className="text-[10px] text-muted-foreground">Customer Success · Superblock HQ</div><Button variant="outline" size="sm" className="mt-2 h-7 bg-card text-[10px]" onClick={()=>toast.success("Avatar uploader opened")}>Change photo</Button></div></div><div className="grid gap-4 pt-5 sm:grid-cols-2"><Field label="Full name" defaultValue="Anika Shah"/><Field label="Display name" defaultValue="Anika"/><Field label="Email" defaultValue="anika@superblock.chat" type="email"/><Field label="Phone" defaultValue="+91 98765 43210"/><div className="sm:col-span-2"><Label className="text-xs">Timezone</Label><Select defaultValue="ist"><SelectTrigger className="mt-1.5"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ist">India Standard Time (GMT+5:30)</SelectItem><SelectItem value="gst">Gulf Standard Time (GMT+4)</SelectItem><SelectItem value="sgt">Singapore Time (GMT+8)</SelectItem></SelectContent></Select></div></div><SaveBar/></SettingsCard>}
function ThemeSettings(){const {theme,setTheme}=useApp(); return <SettingsCard title="Appearance" description="Choose how Superblock Analytics looks in this browser."><div className="grid gap-3 sm:grid-cols-3">{[["light","Light",Sun],["dark","Dark",Moon],["system","System",Palette]].map(([value,label,Icon])=><button key={value as string} onClick={()=>setTheme(value as "light"|"dark"|"system")} className={cn("theme-card",theme===value&&"active")}><div className={cn("theme-preview",value==="dark"&&"dark-preview")}><div className="h-full w-1/4 border-r opacity-60"/><div className="flex-1 p-2"><div className="h-1.5 w-1/2 rounded bg-current opacity-50"/><div className="mt-2 grid grid-cols-2 gap-1"><div className="h-7 rounded border"/><div className="h-7 rounded border"/></div></div></div><div className="mt-3 flex items-center gap-2"><Icon className="size-4"/><span className="text-xs font-medium">{label as string}</span>{theme===value&&<Check className="ml-auto size-3.5 text-primary"/>}</div></button>)}</div><div className="mt-6 rounded-lg border p-4"><div className="flex items-center justify-between"><div><div className="text-xs font-medium">Compact data tables</div><p className="mt-1 text-[10px] text-muted-foreground">Show more records in each viewport.</p></div><Switch defaultChecked onCheckedChange={()=>toast.success("Density preference updated")}/></div></div></SettingsCard>}
function NotificationSettings(){const rows=[["Renewal alerts","When a customer renewal is within 30 days",true],["Billing exceptions","Overdue and failed payment notifications",true],["Usage anomalies","Large changes in customer message volume",true],["Product updates","New Superblock product capabilities",false]] as const;return <SettingsCard title="Notifications" description="Choose the workspace events that reach you."><div className="divide-y rounded-lg border">{rows.map(([title,desc,checked])=><div className="flex items-center justify-between gap-4 p-4" key={title}><div><div className="text-xs font-medium">{title}</div><div className="mt-1 text-[10px] text-muted-foreground">{desc}</div></div><Switch defaultChecked={checked}/></div>)}</div><SaveBar/></SettingsCard>}
function SecuritySettings(){return <SettingsCard title="Login security" description="Control sign-in protection and active sessions."><div className="divide-y rounded-lg border"><div className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">Two-factor authentication</div><div className="mt-1 text-[10px] text-muted-foreground">Require a second verification step when signing in.</div></div><Button variant="outline" size="sm" className="bg-card" onClick={()=>toast.success("2FA setup opened")}>Enable</Button></div><div className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">Login alerts</div><div className="mt-1 text-[10px] text-muted-foreground">Notify me when a new device signs in.</div></div><Switch defaultChecked/></div><div className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">Session timeout</div><div className="mt-1 text-[10px] text-muted-foreground">Automatically sign out inactive sessions.</div></div><Select defaultValue="8"><SelectTrigger className="w-[120px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="1">1 hour</SelectItem><SelectItem value="8">8 hours</SelectItem><SelectItem value="24">24 hours</SelectItem></SelectContent></Select></div></div><div className="mt-5"><SectionHeader title="Active sessions" description="Devices currently signed into your account"/><div className="divide-y rounded-lg border"><div className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">Chrome on macOS <span className="ml-1 text-emerald-600">Current</span></div><div className="mt-1 text-[10px] text-muted-foreground">Mumbai, India · Active now</div></div><Button variant="ghost" size="sm" className="text-xs" disabled>Current session</Button></div><div className="flex items-center justify-between p-4"><div><div className="text-xs font-medium">Safari on iPhone</div><div className="mt-1 text-[10px] text-muted-foreground">Mumbai, India · 2 days ago</div></div><Button variant="outline" size="sm" className="bg-card" onClick={()=>toast.success("Session revoked")}>Revoke</Button></div></div></div></SettingsCard>}
function GenericSettings({section}:{section:string}){const isKeys=section==="API keys";return <SettingsCard title={section} description={`Manage ${section.toLowerCase()} for your Superblock workspace.`}>{isKeys?<div className="rounded-lg border border-dashed p-8 text-center"><span className="mx-auto grid size-10 place-items-center rounded-xl border bg-muted/35"><KeyRound className="size-4"/></span><h3 className="mt-3 text-sm font-semibold">API keys placeholder</h3><p className="mx-auto mt-1 max-w-sm text-[10px] leading-5 text-muted-foreground">Frontend-only preview. Production API keys must be created and stored through a secure backend.</p><Button className="mt-4" disabled>Create API key</Button></div>:<><div className="space-y-4"><Field label={`${section} name`} defaultValue={section==="Workspace"?"Superblock HQ":"Default"}/><div className="flex items-center justify-between rounded-lg border p-4"><div><div className="text-xs font-medium">Enable {section.toLowerCase()}</div><div className="mt-1 text-[10px] text-muted-foreground">Apply this preference across your workspace.</div></div><Switch defaultChecked/></div></div><SaveBar/></>}</SettingsCard>}
function SettingsCard({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <div className="panel p-5 sm:p-6"><div className="border-b pb-5"><h2 className="text-lg font-semibold tracking-[-.025em]">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div><div className="pt-5">{children}</div></div>}
function Field({label,defaultValue,type="text"}:{label:string;defaultValue:string;type?:string}){return <div><Label className="text-xs">{label}</Label><Input className="mt-1.5" defaultValue={defaultValue} type={type}/></div>}
function SaveBar(){const [saving,setSaving]=useState(false);return <div className="mt-6 flex justify-end border-t pt-5"><Button onClick={()=>{setSaving(true);setTimeout(()=>{setSaving(false);toast.success("Settings saved")},650)}} disabled={saving}><Save className="size-4"/>{saving?"Saving…":"Save changes"}</Button></div>}
